# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da2b3495b9445ce9439d97b8abedca0ce67056838fd02cbd951f0b1088aefd1b022329a91b768a3b55e7c205693c1c25049f9dbef75f5671a0257b2d0a2159e7

test:
  secret_key_base: 5a33d84bd0878f87bd35cb5513a6683e54ec2d55f6df1da837d559ddcbe29b26124397b00035505d72e6538f590a3d2ef248321a64343655981232593c179aa8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
